package cn.bugstack.competitoragent.model.dto;

import cn.bugstack.competitoragent.model.enums.TaskNodeStatus;
import cn.bugstack.competitoragent.workflow.contract.QualityDiagnosis;
import cn.bugstack.competitoragent.workflow.contract.QualityDimension;
import cn.bugstack.competitoragent.workflow.contract.RevisionDirective;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Competitor analysis report response")
public class ReportResponse {

    @Schema(description = "Report ID", example = "1")
    private Long id;

    @Schema(description = "Task ID", example = "1")
    private Long taskId;

    @Schema(description = "Report title", example = "AI knowledge product competitor analysis")
    private String title;

    @Schema(description = "Report content in Markdown")
    private String content;

    @Schema(description = "Report summary")
    private String summary;

    @Schema(description = "Latest quality score", example = "85")
    private Integer qualityScore;

    @Schema(description = "Whether the latest quality review passed", example = "true")
    private boolean qualityPassed;

    @Schema(description = "Latest quality issues")
    private List<QualityIssue> qualityIssues;

    @Schema(description = "Initial reviewer checkpoint")
    private ReviewCheckpoint initialReview;

    @Schema(description = "Structured revision plan generated by the reviewer or synthesized from the latest review checkpoint")
    private RevisionPlan revisionPlan;

    @Schema(description = "Whether the rewrite step was executed")
    private boolean rewriteApplied;

    @Schema(description = "Final reviewer checkpoint")
    private ReviewCheckpoint finalReview;

    @Schema(description = "Evidence count", example = "25")
    private Integer evidenceCount;

    @Schema(description = "Evidence list")
    private List<EvidenceInfo> evidences;

    @Schema(description = "Search audit overview aggregated from collector nodes")
    private SearchAuditOverview searchAuditOverview;

    /**
     * Task RAG 审计摘要。
     * 这里直接暴露节点最终落盘的检索上下文文本，方便前端确认 RAG 是否真正参与执行。
     */
    @Schema(description = "Task RAG audit summaries aggregated from task nodes")
    private List<TaskRagAuditInfo> taskRagAudits;

    @Schema(description = "Evidence coverage overview aggregated from structured competitor knowledge")
    private EvidenceCoverageOverview evidenceCoverageOverview;

    /**
     * 章节级证据主链路。
     * 这里直接暴露字段级片段、章节缺口说明和结论级引用摘要，
     * 前端无需再从 writer 输出、coverage 概览和 evidence 列表中自行拼装。
     */
    @Schema(description = "Section and conclusion level evidence bundles")
    private List<SectionEvidenceBundleInfo> sectionEvidenceBundles;

    @Schema(description = "Structured competitor knowledge")
    private List<CompetitorKnowledgeInfo> competitorKnowledges;

    /**
     * 报告诊断聚合模型。
     * 这里把报告正文关联的证据片段、质检诊断和修复建议统一挂到一个出口，
     * 让前端直接消费，不必再自己拼装证据、章节问题和建议动作。
     */
    @Schema(description = "Aggregated report diagnosis model")
    private ReportDiagnosisInfo reportDiagnosis;

    /**
     * 交付中心主路径优先消费的可交付性摘要。
     * 这里直接回答“当前能不能交付、最大问题是什么、下一步建议做什么”，
     * 避免前端先遍历 reportDiagnosis / revisionPlan 再自行拼接用户语言。
     */
    @Schema(description = "Delivery-center summary for the default report path")
    private DeliverySummaryInfo deliverySummary;

    /**
     * 报告主路径优先展示的证据入口。
     * 该对象用于把“先看哪条证据最关键”稳定收口为一个业务可读入口，
     * 而不是让前端自己从 evidence 列表和 section bundle 里推断优先级。
     */
    @Schema(description = "Primary evidence entry point for delivery-center path")
    private EvidenceEntryPointInfo evidenceEntryPoint;

    /**
     * 主路径可直接展示的审计摘要。
     * 这里把检索审计和 Task RAG 审计压缩成简短说明，
     * 用户先理解“为什么当前能下这个结论”，需要深挖时再进入高级诊断对象。
     */
    @Schema(description = "Business-readable audit summary for delivery-center path")
    private AuditSummaryInfo auditSummary;

    @Schema(description = "Created time")
    private LocalDateTime createdAt;

    @Schema(description = "Updated time")
    private LocalDateTime updatedAt;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Aggregated report diagnosis model")
    public static class ReportDiagnosisInfo {
        private Integer diagnosisCount;
        private Integer blockerCount;
        private Integer evidenceGapCount;
        private List<String> sourceUrls;
        private List<ContentEvidenceFragment> contentEvidences;
        private List<DiagnosisSection> sections;
        private List<ReviewNextAction> nextActions;
        private List<RevisionDirectiveInfo> revisionDirectives;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Writer stage evidence fragment returned to report response")
    public static class ContentEvidenceFragment {
        private String stage;
        private String competitorName;
        private String fieldName;
        private String evidenceId;
        private String sourceUrl;
        private String title;
        private String snippet;
        private List<String> issueFlags;
        private EvidenceReference evidence;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Diagnosis section grouped for frontend rendering")
    public static class DiagnosisSection {
        private String section;
        private Boolean evidenceInsufficient;
        private List<String> sourceUrls;
        private List<String> repairSuggestions;
        private List<DiagnosisItem> diagnoses;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Diagnosis item linked with evidence references")
    public static class DiagnosisItem {
        private String reviewStage;
        private QualityDiagnosis diagnosis;
        private List<EvidenceReference> evidenceReferences;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Lightweight evidence reference nested in diagnosis model")
    public static class EvidenceReference {
        private String evidenceId;
        private String title;
        private String url;
        private String competitorName;
        private String sourceType;
        private String contentSnippet;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Delivery-center summary for the default report path")
    public static class DeliverySummaryInfo {
        private Boolean readyForDelivery;
        private String deliveryStatus;
        private String summary;
        private String primaryIssue;
        private String recommendedAction;
        private Integer blockerCount;
        private Integer evidenceGapCount;
        private List<String> sourceUrls;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Primary evidence entry point for delivery-center path")
    public static class EvidenceEntryPointInfo {
        private String summary;
        private String sectionKey;
        private String sectionTitle;
        private String evidenceId;
        private String title;
        private String url;
        private String sourceType;
        private List<String> sourceUrls;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Business-readable audit summary for delivery-center path")
    public static class AuditSummaryInfo {
        private String summary;
        private String searchAuditSummary;
        private String taskRagAuditSummary;
        private List<String> sourceUrls;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Field-level evidence detail nested inside a section evidence bundle")
    public static class FieldEvidenceDetail {
        private String fieldName;
        private String fieldLabel;
        private String coverageStatus;
        private String gapComment;
        private String evidenceId;
        private String sourceUrl;
        private String title;
        private String snippet;
        private List<String> issueFlags;
        private EvidenceReference evidence;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Section or conclusion evidence bundle projected for the report interface")
    public static class SectionEvidenceBundleInfo {
        private String stage;
        private String sectionType;
        private String sectionKey;
        private String sectionTitle;
        private String summary;
        private String gapSummary;
        private Boolean hasGap;
        private List<String> fieldNames;
        private List<String> missingFields;
        private List<String> sourceUrls;
        private List<String> issueFlags;
        private List<FieldEvidenceDetail> fields;
        private List<EvidenceReference> evidenceReferences;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Review checkpoint")
    public static class ReviewCheckpoint {
        private String nodeName;
        private TaskNodeStatus nodeStatus;
        private Integer score;
        private Boolean passed;
        private Boolean requiresHumanIntervention;
        private Boolean autoRewriteAllowed;
        private String summary;
        private List<QualityDimension> dimensions;
        private List<QualityDiagnosis> diagnoses;
        private List<QualityIssue> issues;
        private List<ReviewNextAction> nextActions;
        private List<RevisionDirective> revisionDirectives;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Structured revision directive projected to report response")
    public static class RevisionDirectiveInfo {
        private String category;
        private String actionType;
        private String priority;
        private String targetNode;
        private String targetSection;
        private String summary;
        private String searchFeedback;
        private List<String> searchQueries;
        private List<String> sourceUrls;
        private String expectedOutcome;

        /**
         * 把修订指令投影层继续收口成稳定契约。
         * 这样前端拿到的 sourceUrls / searchQueries 不会再混入空值、重复值，
         * 也能保证报告页把“修订路径建议”直接挂到业务可读来源上。
         */
        public RevisionDirectiveInfo normalized() {
            return RevisionDirectiveInfo.builder()
                    .category(normalizeText(category))
                    .actionType(normalizeText(actionType))
                    .priority(normalizeText(priority))
                    .targetNode(normalizeText(targetNode))
                    .targetSection(normalizeText(targetSection))
                    .summary(normalizeText(summary))
                    .searchFeedback(normalizeText(searchFeedback))
                    .searchQueries(normalizeDistinctTexts(searchQueries))
                    .sourceUrls(normalizeDistinctTexts(sourceUrls))
                    .expectedOutcome(normalizeText(expectedOutcome))
                    .build();
        }

        private List<String> normalizeDistinctTexts(List<String> values) {
            if (values == null || values.isEmpty()) {
                return List.of();
            }
            LinkedHashSet<String> normalized = new LinkedHashSet<>();
            for (String value : values) {
                String text = normalizeText(value);
                if (text != null) {
                    normalized.add(text);
                }
            }
            return new ArrayList<>(normalized);
        }

        private String normalizeText(String value) {
            return value == null || value.isBlank() ? null : value.trim();
        }
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Quality issue")
    public static class QualityIssue {
        private String type;
        private String section;
        private String severity;
        private String level;
        private String dimensionCode;
        private String dimensionName;
        private String evidenceBasis;
        private List<String> evidenceIds;
        private List<String> sourceUrls;
        private String suggestion;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Recommended action after a failed final review")
    public static class ReviewNextAction {
        private String title;
        private String description;
        private String actionType;
        private String targetNode;
        private String priority;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Evidence info")
    public static class EvidenceInfo {
        private String evidenceId;
        private String title;
        private String url;
        private String contentSnippet;
        private String competitorName;
        private LocalDateTime collectedAt;
        private String sourceType;
        private String discoveryMethod;
        private String sourceDomain;
        private String discoveryReason;
        private String publishedAt;
        private Double sourceScore;
        private Boolean verified;
        private String verificationReason;
        private String searchQuery;
        private String searchEngine;
        private Integer resultRank;
        private String browserTraceId;
        private String selectionReason;
        private String selectionStage;
        private List<String> matchedSignals;
        private Map<String, Object> pageMetadata;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Task RAG audit summary")
    public static class TaskRagAuditInfo {
        private String nodeName;
        private String agentType;
        private String taskRagContext;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Search audit overview")
    public static class SearchAuditOverview {
        private Integer collectorNodeCount;
        private Integer traceRecordedCount;
        private Integer checkpointRecoveredCount;
        private Integer degradedCount;
        private Integer providerFallbackCount;
        private Integer browserBlockedCount;
        private Integer plannedCandidateCount;
        private Integer verifiedCandidateCount;
        private Integer supplementedCandidateCount;
        private Integer selectedCandidateCount;
        private List<CollectorSearchAudit> collectors;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Evidence coverage overview")
    public static class EvidenceCoverageOverview {
        private Integer totalFields;
        private Integer traceableFields;
        private Integer missingEvidenceFields;
        private Integer emptyFields;
        private List<SectionEvidenceCoverage> sections;
        private List<CompetitorEvidenceCoverage> competitors;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Section-level evidence coverage")
    public static class SectionEvidenceCoverage {
        private String sectionKey;
        private String sectionTitle;
        private Integer totalFields;
        private Integer traceableFields;
        private Integer missingEvidenceFields;
        private Integer emptyFields;
        private List<String> missingFields;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Competitor-level evidence coverage")
    public static class CompetitorEvidenceCoverage {
        private String competitorName;
        private Integer totalFields;
        private Integer traceableFields;
        private Integer missingEvidenceFields;
        private Integer emptyFields;
        private List<String> missingSections;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Collector-level search audit")
    public static class CollectorSearchAudit {
        private String nodeName;
        private TaskNodeStatus nodeStatus;
        private String competitorName;
        private String sourceType;
        private Boolean traceRecorded;
        private String auditMessage;
        private String supplementMethod;
        private Boolean resumedFromCheckpoint;
        private String checkpointSource;
        private Boolean degraded;
        private String degradationReason;
        private Boolean providerFallbackUsed;
        private String fallbackDecision;
        private String browserTraceId;
        private String browserBlockedReason;
        private Integer browserBlockedCount;
        private String recoveryCheckpoint;
        private Integer plannedCandidateCount;
        private Integer verifiedCandidateCount;
        private Integer supplementedCandidateCount;
        private Integer selectedCandidateCount;
        private List<String> selectedUrls;
        private String errorMessage;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Competitor knowledge summary")
    public static class CompetitorKnowledgeInfo {
        private String competitorName;
        private String officialUrl;
        private String summary;
        private String positioning;
        private List<String> targetUsers;
        private Map<String, Object> pricing;
        private List<String> sourceUrls;
        private Map<String, Object> evidenceCoverage;
    }
}
