package cn.bugstack.competitoragent.model.dto;

import cn.bugstack.competitoragent.model.enums.TaskNodeStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Competitor analysis report response")
public class ReportResponse {

    @Schema(description = "Report ID", example = "1")
    private Long id;

    @Schema(description = "Task ID", example = "1")
    private Long taskId;

    @Schema(description = "Report title", example = "AI knowledge product competitor analysis")
    private String title;

    @Schema(description = "Report content in Markdown")
    private String content;

    @Schema(description = "Report summary")
    private String summary;

    @Schema(description = "Latest quality score", example = "85")
    private Integer qualityScore;

    @Schema(description = "Whether the latest quality review passed", example = "true")
    private boolean qualityPassed;

    @Schema(description = "Latest quality issues")
    private List<QualityIssue> qualityIssues;

    @Schema(description = "Initial reviewer checkpoint")
    private ReviewCheckpoint initialReview;

    @Schema(description = "Revision plan generated by the reviewer")
    private RevisionPlan revisionPlan;

    @Schema(description = "Whether the rewrite step was executed")
    private boolean rewriteApplied;

    @Schema(description = "Final reviewer checkpoint")
    private ReviewCheckpoint finalReview;

    @Schema(description = "Evidence count", example = "25")
    private Integer evidenceCount;

    @Schema(description = "Evidence list")
    private List<EvidenceInfo> evidences;

    @Schema(description = "Structured competitor knowledge")
    private List<CompetitorKnowledgeInfo> competitorKnowledges;

    @Schema(description = "Created time")
    private LocalDateTime createdAt;

    @Schema(description = "Updated time")
    private LocalDateTime updatedAt;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Review checkpoint")
    public static class ReviewCheckpoint {
        private String nodeName;
        private TaskNodeStatus nodeStatus;
        private Integer score;
        private Boolean passed;
        private String summary;
        private List<QualityIssue> issues;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Quality issue")
    public static class QualityIssue {
        private String type;
        private String section;
        private String severity;
        private String suggestion;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Evidence info")
    public static class EvidenceInfo {
        private String evidenceId;
        private String title;
        private String url;
        private String contentSnippet;
        private String competitorName;
        private LocalDateTime collectedAt;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Competitor knowledge summary")
    public static class CompetitorKnowledgeInfo {
        private String competitorName;
        private String officialUrl;
        private String summary;
        private String positioning;
        private List<String> targetUsers;
        private Map<String, Object> pricing;
        private List<String> sourceUrls;
        private Map<String, Object> evidenceCoverage;
    }
}
