package cn.bugstack.competitoragent.model.dto;

import cn.bugstack.competitoragent.model.enums.TaskNodeStatus;
import cn.bugstack.competitoragent.workflow.contract.QualityDiagnosis;
import cn.bugstack.competitoragent.workflow.contract.QualityDimension;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Competitor analysis report response")
public class ReportResponse {

    @Schema(description = "Report ID", example = "1")
    private Long id;

    @Schema(description = "Task ID", example = "1")
    private Long taskId;

    @Schema(description = "Report title", example = "AI knowledge product competitor analysis")
    private String title;

    @Schema(description = "Report content in Markdown")
    private String content;

    @Schema(description = "Report summary")
    private String summary;

    @Schema(description = "Latest quality score", example = "85")
    private Integer qualityScore;

    @Schema(description = "Whether the latest quality review passed", example = "true")
    private boolean qualityPassed;

    @Schema(description = "Latest quality issues")
    private List<QualityIssue> qualityIssues;

    @Schema(description = "Initial reviewer checkpoint")
    private ReviewCheckpoint initialReview;

    @Schema(description = "Revision plan generated by the reviewer")
    private RevisionPlan revisionPlan;

    @Schema(description = "Whether the rewrite step was executed")
    private boolean rewriteApplied;

    @Schema(description = "Final reviewer checkpoint")
    private ReviewCheckpoint finalReview;

    @Schema(description = "Evidence count", example = "25")
    private Integer evidenceCount;

    @Schema(description = "Evidence list")
    private List<EvidenceInfo> evidences;

    @Schema(description = "Search audit overview aggregated from collector nodes")
    private SearchAuditOverview searchAuditOverview;

    @Schema(description = "Evidence coverage overview aggregated from structured competitor knowledge")
    private EvidenceCoverageOverview evidenceCoverageOverview;

    @Schema(description = "Structured competitor knowledge")
    private List<CompetitorKnowledgeInfo> competitorKnowledges;

    /**
     * 报告诊断聚合模型。
     * 这里把报告正文关联的证据片段、质检诊断和修复建议统一挂到一个出口，
     * 让前端直接消费，不必再自己拼装证据、章节问题和建议动作。
     */
    @Schema(description = "Aggregated report diagnosis model")
    private ReportDiagnosisInfo reportDiagnosis;

    @Schema(description = "Created time")
    private LocalDateTime createdAt;

    @Schema(description = "Updated time")
    private LocalDateTime updatedAt;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Aggregated report diagnosis model")
    public static class ReportDiagnosisInfo {
        private Integer diagnosisCount;
        private Integer blockerCount;
        private Integer evidenceGapCount;
        private List<String> sourceUrls;
        private List<ContentEvidenceFragment> contentEvidences;
        private List<DiagnosisSection> sections;
        private List<ReviewNextAction> nextActions;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Writer stage evidence fragment returned to report response")
    public static class ContentEvidenceFragment {
        private String stage;
        private String competitorName;
        private String fieldName;
        private String evidenceId;
        private String sourceUrl;
        private String title;
        private String snippet;
        private List<String> issueFlags;
        private EvidenceReference evidence;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Diagnosis section grouped for frontend rendering")
    public static class DiagnosisSection {
        private String section;
        private Boolean evidenceInsufficient;
        private List<String> sourceUrls;
        private List<String> repairSuggestions;
        private List<DiagnosisItem> diagnoses;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Diagnosis item linked with evidence references")
    public static class DiagnosisItem {
        private String reviewStage;
        private QualityDiagnosis diagnosis;
        private List<EvidenceReference> evidenceReferences;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Lightweight evidence reference nested in diagnosis model")
    public static class EvidenceReference {
        private String evidenceId;
        private String title;
        private String url;
        private String competitorName;
        private String sourceType;
        private String contentSnippet;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Review checkpoint")
    public static class ReviewCheckpoint {
        private String nodeName;
        private TaskNodeStatus nodeStatus;
        private Integer score;
        private Boolean passed;
        private Boolean requiresHumanIntervention;
        private Boolean autoRewriteAllowed;
        private String summary;
        private List<QualityDimension> dimensions;
        private List<QualityDiagnosis> diagnoses;
        private List<QualityIssue> issues;
        private List<ReviewNextAction> nextActions;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Quality issue")
    public static class QualityIssue {
        private String type;
        private String section;
        private String severity;
        private String level;
        private String dimensionCode;
        private String dimensionName;
        private String evidenceBasis;
        private List<String> evidenceIds;
        private List<String> sourceUrls;
        private String suggestion;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Recommended action after a failed final review")
    public static class ReviewNextAction {
        private String title;
        private String description;
        private String actionType;
        private String targetNode;
        private String priority;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Evidence info")
    public static class EvidenceInfo {
        private String evidenceId;
        private String title;
        private String url;
        private String contentSnippet;
        private String competitorName;
        private LocalDateTime collectedAt;
        private String sourceType;
        private String discoveryMethod;
        private String sourceDomain;
        private String discoveryReason;
        private String publishedAt;
        private Double sourceScore;
        private Boolean verified;
        private String verificationReason;
        private String searchQuery;
        private String searchEngine;
        private Integer resultRank;
        private String browserTraceId;
        private String selectionReason;
        private String selectionStage;
        private List<String> matchedSignals;
        private Map<String, Object> pageMetadata;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Search audit overview")
    public static class SearchAuditOverview {
        private Integer collectorNodeCount;
        private Integer traceRecordedCount;
        private Integer checkpointRecoveredCount;
        private Integer degradedCount;
        private Integer providerFallbackCount;
        private Integer browserBlockedCount;
        private Integer plannedCandidateCount;
        private Integer verifiedCandidateCount;
        private Integer supplementedCandidateCount;
        private Integer selectedCandidateCount;
        private List<CollectorSearchAudit> collectors;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Evidence coverage overview")
    public static class EvidenceCoverageOverview {
        private Integer totalFields;
        private Integer traceableFields;
        private Integer missingEvidenceFields;
        private Integer emptyFields;
        private List<SectionEvidenceCoverage> sections;
        private List<CompetitorEvidenceCoverage> competitors;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Section-level evidence coverage")
    public static class SectionEvidenceCoverage {
        private String sectionKey;
        private String sectionTitle;
        private Integer totalFields;
        private Integer traceableFields;
        private Integer missingEvidenceFields;
        private Integer emptyFields;
        private List<String> missingFields;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Competitor-level evidence coverage")
    public static class CompetitorEvidenceCoverage {
        private String competitorName;
        private Integer totalFields;
        private Integer traceableFields;
        private Integer missingEvidenceFields;
        private Integer emptyFields;
        private List<String> missingSections;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Collector-level search audit")
    public static class CollectorSearchAudit {
        private String nodeName;
        private TaskNodeStatus nodeStatus;
        private String competitorName;
        private String sourceType;
        private Boolean traceRecorded;
        private String auditMessage;
        private String supplementMethod;
        private Boolean resumedFromCheckpoint;
        private String checkpointSource;
        private Boolean degraded;
        private String degradationReason;
        private Boolean providerFallbackUsed;
        private String fallbackDecision;
        private String browserTraceId;
        private String browserBlockedReason;
        private Integer browserBlockedCount;
        private String recoveryCheckpoint;
        private Integer plannedCandidateCount;
        private Integer verifiedCandidateCount;
        private Integer supplementedCandidateCount;
        private Integer selectedCandidateCount;
        private List<String> selectedUrls;
        private String errorMessage;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Competitor knowledge summary")
    public static class CompetitorKnowledgeInfo {
        private String competitorName;
        private String officialUrl;
        private String summary;
        private String positioning;
        private List<String> targetUsers;
        private Map<String, Object> pricing;
        private List<String> sourceUrls;
        private Map<String, Object> evidenceCoverage;
    }
}
